### ISSUE TITLE
enhancement - two more versions, without any pop-up

### ISSUE THREAD

**Issue by john-catalano** [Rebel1898/4chan-Image-expander#1]
This does the job. Thank you. But I never need to remove superfluous images. I'd like it if the script just expanded all images without any pop-up.

For now, I've just replace the line...

`var r = confirm("Are you going to download images in this session?\n OK will remove unnecesary images to improve bulk download");`

with...

`var r = false;`

**Comment by Rebel1898** [comment]
Ey! Thank you for your interest. Glad this is useful to you. 
I have optimized the script, so now, there is no more confirm and both removal of unnecesary images and expansion of image happens on every call.
